sudo: true
dist: trusty
cache:
  directories:
    - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_f533ce29e2e6_key -iv $encrypted_f533ce29e2e6_iv
  -in assets/server.key.enc -out assets/server.key -d
before_script:
- npm install -g gulp-cli
- npm install
script:
#- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg
#- sfdx force:source:push -u ciorg
#- sfdx force:apex:test:run -u ciorg -c -r human
#- sfdx force:org:delete -u ciorg -p
- gulp init
- gulp check:fields
- gulp test
after_script:
- gulp clean